//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WV.Windows.HostObject {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HOResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HOResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WV.Windows.HostObject.HOResources", typeof(HOResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a const HONAME = &apos;-HostObjectName-&apos;;
        ///const NAME = &apos;-Name-&apos;;
        ///const WV = window.chrome.webview.hostObjects;
        ///
        ///window[NAME] = {
        ///    WV,
        ///    SYNC: WV.sync[HONAME],
        ///    ASYNC: WV[HONAME]
        ///}.
        /// </summary>
        internal static string HOScript1 {
            get {
                return ResourceManager.GetString("HOScript1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a const WIN = window;
        ///const NAME = &apos;-Name-&apos;;
        ///const WV = WIN[NAME].WV;
        ///const SYNC = WIN[NAME].SYNC;
        ///const ASYNC = WIN[NAME].SYNC;
        ///const MASTER = CreatePlainObject();
        ///const TO_STRING = Object.prototype.toString;
        ///const STRINGIFY = JSON.stringify;
        ///const ARRAY_FROM = Array.from;
        ///const IS_ARRAY = Array.isArray;
        ///const ARRAYS = [&apos;Uint8Array&apos;, &apos;Uint8ClampedArray&apos;, &apos;Int8Array&apos;, &apos;Uint16Array&apos;, &apos;Int16Array&apos;, &apos;Uint32Array&apos;, &apos;Int32Array&apos;, &apos;Float32Array&apos;, &apos;Float64Array&apos;, &apos;BigUint64Array&apos;, &apos;BigInt64Array&apos;];
        ///
        ///WIN[ [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HOScript2 {
            get {
                return ResourceManager.GetString("HOScript2", resourceCulture);
            }
        }
    }
}
